image: python:3.8

stages:
  - lint
  - tests

lint:
    stage: lint
    script:
      - make install
      - make lint

tests:
    stage: tests
    script:
      - ls
      - make install_c_libs && make install # && make download_weights
      - make run_tests