image: python:3.8

stages:
  - lint
  - tests

lint:
    stage: lint
    script:
      - python3 -m pip install -r requirements.txt
      - make lint

#tests:
#    stage: tests
#    script:
#      - ls
#      - make install && make download_weights
#      - make run_tests